<?xml version="1.0"?>
<package format="3">
  <name>rby1_slam</name>
  <version>0.0.1</version>
  <description>SLAM launch package for RB-Y1</description>
  <maintainer email="rby.support@rainbow-robotica.com">nvidia</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
